### ISSUE TITLE
Publish the mailin-api-ruby as a gem?

### ISSUE THREAD

**Issue by grekko** [mailin-api/mailin-api-ruby#1]
Hi! I'd like to use the sendinblue service via your ruby api client. Are you planning to publish the client wrapped as a rubygem? That would help a lot to maintain the library code.

**Comment by ekta-slit** [comment]
Hello Gregory,

Thank you for contacting us.

We have already published our SendinBlue API V2 Ruby GEM :)

Please download it here: https://rubygems.org/gems/sendinblue

Regards,
SendinBlue Team

**Comment by grekko** [comment]
Ah.. I was just wondering why there is no *.gemspec in the repo! :)
